### ISSUE TITLE
Read frequency database on Familias and FamLinkX format

### ISSUE THREAD

**Issue by thoree** [magnusdv/forrel#28]
It would be  nice to be able read tab separated asci files exported from Windows Familias and FamLinkX on the below format to define ped markers

DXS10148
13.3	0.4
14	0.3
17	0.3

DXS10135
16	0.5
16.1	0.5
...

**Comment by knifecake** [comment]
I believe there is a function inside the *epGUI* code that does this, namely `attachAlleleFrequenciesToPedigree.familias`. It takes a pedigree `ped` and a file path `path` and attaches the frequency data found in the file at `path` to the pedigree `ped`. I tested it with the sample files that @thoree provided for *epGUI* and it appeared to work fine.

Something we could do is move just this function to the main `forrel` branch so that it is available even though the *epGUI* is still not ready. I can create a new branch and incorporate this function to say `R/readFam.R`.

Here is the link to the file that contains the function: https://github.com/magnusdv/forrel/blob/shiny-gui/inst/exclusionPowerUI/importAdapters/familias-import-adapter.R#L20

**Comment by magnusdv** [comment]
This functionality is now implemented in `pedtools::readFrequencyDatabase()`.
